#!/bin/zsh
export CONFIG_PATH=/barrett/scratch/donovick/config
export ZDOTDIR=$CONFIG_PATH/zsh/dotdir

# load env
source $CONFIG_PATH/shells/env.sh

# run start up commands
source $CONFIG_PATH/shells/startup.sh

# load aliases
source $CONFIG_PATH/shells/maps.sh

