#!/bin/zsh
source /afs/cs/etc/skel/.zshrc

if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  . /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Lines configured by zsh-newuser-install
HISTFILE=$XDG_CONFIG_HOME/zsh/history
HISTSIZE=1000
SAVEHIST=1000
setopt notify
unsetopt appendhistory autocd beep extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/afs/cs.stanford.edu/u/donovick/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

autoload -Uz promptinit
promptinit

ZSH_CACHE_DIR=$XDG_CONFIG_HOME/zsh/cache
#  :completion:<func>:<completer>:<command>:<argument>:<tag>
#menu
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''

#fuzz
zstyle ':completion:*' completer _complete _correct #_approximate
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
#zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'

#cache
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

#ignore
zstyle ':completion:*:*:*:*:*(files|directories)' ignored-patterns '(__pycache__|*.pyc)'

# show ignored
zstyle '*' single-ignored show


PROMPT="%n@%m:%(5~|…/%4~|%~)%# "

#load aliases
source $XDG_CONFIG_HOME/shells/maps.sh
